[nnstreamer] Fix the QA issue for the LICENSE on kirkstone
QA issue occurs for the nnstreamer on kirkstone. So it should be
updated from 'LGPLv2.1' to 'LGPL-2.1-only' properly.
Refer to below license changes for the yocto kirkstone.
https://docs.yoctoproject.org/dev/migration-guides/migration-4.0.html#license-changes.

<ERROR Messages>
ERROR: nnstreamer-2.1.0+gitAUTOINC+b251e9bc6b-r0 do_package_qa: QA Issue: Recipe LICENSE includes obsolete licenses LGPLv2.1 [obsolete-license]
ERROR: nnstreamer-2.1.0+gitAUTOINC+b251e9bc6b-r0 do_package_qa: Fatal QA errors were found, failing task.

Signed-off-by: Jimmy Ohn <yongjin.ohn@lge.com>